'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class registratie

    '''<summary>
    '''naam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents naam As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''voornaam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents voornaam As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents email As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''wachtwoord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wachtwoord As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''wachtwoordbevestigen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wachtwoordbevestigen As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''rol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rol As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ckbBeheerder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbBeheerder As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblErrormessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrormessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnNieuweGebruiker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNieuweGebruiker As Global.System.Web.UI.WebControls.Button
End Class
