'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class bestellingPlaatsen

    '''<summary>
    '''dsBestelling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsBestelling As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsKlanten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsKlanten As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsModel As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsTechnicus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsTechnicus As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsVerkoper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsVerkoper As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''grvBestelling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvBestelling As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''panelBestellingPlaatsen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelBestellingPlaatsen As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dpdKlanten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpdKlanten As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dpdModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpdModel As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAantal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAantal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtExtraInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExtraInfo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dpdVerkoper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpdVerkoper As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dpdTechnicus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpdTechnicus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''afleveringsdatum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents afleveringsdatum As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''lblErrorMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnNieuweBestelling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNieuweBestelling As Global.System.Web.UI.WebControls.Button
End Class
